// Textos de la aplicación. El prompt y el Markdown de la IA quedan fuera de este catálogo.
export const TEXTS_GENERAL = {
    errorPrefix: 'Error:',
    sourceNotFound: (provider: string) => `No se encontraron datos en ${provider}`,
    sourceInvalidKey: (provider: string) => `API Key incorrecta para ${provider}`,
    sourceUnavailable: (provider: string) => `${provider} no está disponible en este momento`,
    sourceUnknownError: (provider: string) => `Error desconocido en ${provider}`,
    iocNotFound: (provider?: string) => `El IoC no existe en los registros de ${provider}.`,
    invalidProviderKey: (provider?: string) => `La API Key de ${provider} es incorrecta.`,
    providerUnavailable: (provider?: string) => `La API de ${provider} no está disponible en este momento.`,
    invalidAiKey: (provider?: string) => `La API Key de ${provider} no es válida o no tiene permisos suficientes.`,
    aiUnavailable: (provider?: string) => `El servicio de ${provider} no está disponible en este momento.`,
    invalidKeySources: (count: number) => `${count} ${count === 1 ? 'fuente' : 'fuentes'} con API Key no válida`,
    noDataSources: (count: number) => `${count} ${count === 1 ? 'fuente' : 'fuentes'} sin datos para este IoC`,
    brands: {
        cubepath: 'Cubepath', astro: 'Astro', react: 'React', tailwind: 'Tailwind CSS',
        openrouter: 'OpenRouter', virustotal: 'VirusTotal', abuseipdb: 'AbuseIPDB',
        polyswarm: 'PolySwarm', robtex: 'Robtex', poolside: 'Poolside', novita: 'NovitaAI',
    },
    socialLabels: {
        linkedin: 'LinkedIn', github: 'GitHub', hackthebox: 'HackTheBox', x: 'X/Twitter', email: 'Contactame',
    },
    modelLabels: {
        auto: 'Default - OpenRouter (Auto)', free: 'OpenRouter (Free)',
        poolside: 'Poolside: Laguna XS 2.1 (free)', novita: 'NovitaAI: Ling-3.0-flash (free)',
    },
    statusLabels: {
        idle: 'idle', analyzing: 'analyzing', streaming: 'streaming', done: 'done', error: 'error',
    },
    searchDescription: 'Envía una IP, un dominio o un hash y un modelo de IA redacta un veredicto del IoC basandose en la información de distintas fuentes de datos de inteligencia de amenazas y analizadores de IoC.',
    iocLabel: 'Indicador de compromiso',
    analyzingButton: 'Analizando...',
    analyzeButton: 'Iniciar análisis',
    iocPlaceholder: 'Ejemplo: 8.8.8.8, 2001:4860:4860::8888, example.org o 44d88612fea8a8f36de82e1278abb02f',
    iocTypes: ['IPv4 / IPv6', 'Dominio', 'MD5', 'SHA1', 'SHA256'],
    supportedIocTypes: 'Tipos de IoC soportados',
    modelLabel: 'Modelo:',
    loadingModel: 'Cargando modelo...',
    configureApiKeys: 'Configurar API keys',
    apiKeysButton: 'API keys',
    openRouterKeyHint: 'Requerida para el análisis de IA',
    virusTotalKeyHint: 'Usada para IP, dominio y hash',
    abuseIpDbKeyHint: 'Usada para análisis de IP',
    polySwarmKeyHint: 'Usada para análisis de hash',
    openRouterKeyPlaceholder: 'sk-or-...',
    virusTotalKeyPlaceholder: 'Tu API key de VirusTotal',
    abuseIpDbKeyPlaceholder: 'Tu API key de AbuseIPDB',
    polySwarmKeyPlaceholder: 'Tu API key de PolySwarm',
    settingsTitle: 'Configuración',
    apiKeysTitle: 'API Keys',
    close: 'Cerrar',
    keysStorageNotice: 'Las claves se guardan únicamente en tu navegador. Si las dejas vacías, el servidor usará las configuradas por defecto.',
    hide: 'Ocultar',
    show: 'Mostrar',
    clearKeys: 'Limpiar todas',
    cancel: 'Cancelar',
    save: 'Guardar',
    resultsTitle: 'Resultados del análisis',
    resultIocLabel: 'IoC:',
    resultTypeLabel: 'Tipo:',
    resultModelLabel: 'Modelo:',
    analysisErrorTitle: 'Error en el análisis',
    preparingAnalysis: 'Preparando contexto y consultando la IA...\n',
    streamUnavailable: 'Streaming no disponible en la respuesta',
    unknownError: 'Error desconocido',
    clientAnalysisError: 'No se pudo completar el análisis',
    rateLimitError: "Too many requests",
    missingIoc: "Falta el parámetro de IoC",
    invalidIoc: "Tipo de IoC desconocido",
    iocAnalysisError: 'No se pudo completar la consulta de fuentes del IoC.',
    aiAnalysisError: 'No se pudo completar el análisis con la IA.',
    modelError: 'El modelo devolvió un error inesperado durante el análisis.',
    analysisError: 'No se pudo completar el análisis.',
    unsupportedIoc: 'Tipo de IoC no soportado',
    emptyOpenRouterResponse: 'Respuesta sin cuerpo de OpenRouter',
    unsupportedPolySwarmHash: 'Unsupported hash type for PolySwarm',
    siteName: "CyberThreat AI",
    siteDescription: "Aplicación desarrollada para el Hackaton de Midudev + CubePath, con el objetivo de demostrar mis habilidades en desarrollo web y ciberseguridad.",
    repositoryLink: 'Repo',
    aboutMeLink: 'Sobre mí',
    hackathonTitle: 'Hackaton Midudev - CubePath',
    poweredBy: 'Powered by',
    licenseNotice: 'Este proyecto está licenciado bajo los términos de la',
    licenseName: 'GNU General Public License v3.0',
    homeTitle: 'Inicio',
    heroStart: '¡Comienza tu ',
    heroIndicators: 'investigación de indicadores',
    heroBridge: ' de compromiso a través de ',
    heroModels: 'modelos LLM',
    heroEnd: '!',
    emptyMessages: {
        idle: [
            'Esperando un IoC para comenzar el análisis.',
            'Lista para inspeccionar IPs, dominios y hashes.',
            'Introduce un indicador y levantaré evidencia técnica.'
        ],
        analyzing: [
            'Investigando el indicador y cruzando señales iniciales...',
            'Recabando datos de las fuentes de inteligencia...',
            'Consultando reputación, contexto y trazas disponibles...',
            'Buscando coincidencias y patrones de riesgo...'
        ],
        streaming: [
            'La IA está redactando la respuesta...',
            'Sintetizando hallazgos y priorizando señales relevantes...',
            'Consultando contexto adicional en la deep web...',
            'Consolidando evidencias para emitir un veredicto...'
        ],
        done: [
            'El análisis terminó, pero todavía no hay texto para mostrar.',
            'La respuesta llegó vacía; revisa la siguiente consulta.',
            'No se recibió contenido visible del modelo en esta ejecución.'
        ],
        error: [
            'La consulta se interrumpió antes de devolver contenido.',
            'Hubo un error durante el análisis del IoC.',
            'No fue posible completar la respuesta de la IA.'
        ]
    },
    statusMessages: {
        idle: 'Envía un IoC para iniciar el análisis',
        analyzing: 'Recolectando evidencias de las herramientas...',
        streaming: 'La IA está redactando la respuesta...',
        done: 'Respuesta completada',
        error: 'Algo salió mal durante el análisis',
    },
};
